apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-test-app
spec:
  replicas: 2  # Number of pods
  selector:
    matchLabels:
      app: v1
  template:
    metadata:
      labels:
        app: v1
    spec:
      containers:
      - name: v1
        image: v1:latest
        imagePullPolicy: Never  # Tell Kubernetes not to pull from a registry
        # image: vikash95/kubernetes-test-app:latest
        resources:
          limits:
            memory: "64Mi"
            cpu: "200m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: v1
spec:
  selector:
    app: v1
  ports:
  - port: 8080
    targetPort: 5000